// Code generated by MockGen. DO NOT EDIT.
// Source: ./server.go
//
// Generated by this command:
//
//	mockgen -source ./server.go -destination=./mocks/server.go -package=mock_server
//

// Package mock_server is a generated GoMock package.
package mock_server

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockwalletService is a mock of walletService interface.
type MockwalletService struct {
	ctrl     *gomock.Controller
	recorder *MockwalletServiceMockRecorder
	isgomock struct{}
}

// MockwalletServiceMockRecorder is the mock recorder for MockwalletService.
type MockwalletServiceMockRecorder struct {
	mock *MockwalletService
}

// NewMockwalletService creates a new mock instance.
func NewMockwalletService(ctrl *gomock.Controller) *MockwalletService {
	mock := &MockwalletService{ctrl: ctrl}
	mock.recorder = &MockwalletServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwalletService) EXPECT() *MockwalletServiceMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockwalletService) CreateWallet(ctx context.Context) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockwalletServiceMockRecorder) CreateWallet(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockwalletService)(nil).CreateWallet), ctx)
}

// Deposit mocks base method.
func (m *MockwalletService) Deposit(ctx context.Context, walletID uuid.UUID, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", ctx, walletID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deposit indicates an expected call of Deposit.
func (mr *MockwalletServiceMockRecorder) Deposit(ctx, walletID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockwalletService)(nil).Deposit), ctx, walletID, amount)
}

// GetBalance mocks base method.
func (m *MockwalletService) GetBalance(ctx context.Context, walletID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, walletID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockwalletServiceMockRecorder) GetBalance(ctx, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockwalletService)(nil).GetBalance), ctx, walletID)
}

// Withdraw mocks base method.
func (m *MockwalletService) Withdraw(ctx context.Context, walletID uuid.UUID, amount int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdraw", ctx, walletID, amount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdraw indicates an expected call of Withdraw.
func (mr *MockwalletServiceMockRecorder) Withdraw(ctx, walletID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdraw", reflect.TypeOf((*MockwalletService)(nil).Withdraw), ctx, walletID, amount)
}
